### ISSUE TITLE
Build failing on master

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/ArrayViews.jl#20]
This is causing problems downstream (e.g. StatsBase).

**Comment by lindahua** [comment]
I will try to take a look this evening.

**Comment by lindahua** [comment]
Looks like it is something related to `convert` and `unsafe_convert` for pointers.

**Comment by andreasnoack** [comment]
My bad. I forgot to import `unsafe_convert`. It is fixed now. I'll also tag a new version.
