### ISSUE TITLE
Indexing with integer array

### ISSUE THREAD

**Issue by dpo** [JuliaLang/ArrayViews.jl#22]
````JULIA
julia> a = rand(5,5);
julia> view(a, :, [1,3,4])
ERROR: `view` has no method matching view(::Array{Float64,2}, ::Colon, ::Array{Int64,1})
````

Is this expected?

Thanks.

**Comment by andreasnoack** [comment]
Yes. The views have to be with ranges. You can use the `SubArray`s in base with your kind of indexing, but then you cannot call BLAS. Julia will fall back to a slower generic multiplication method when using `*`.

**Comment by dpo** [comment]
The point was precisely to call BLAS (https://groups.google.com/forum/?fromgroups=#!topic/julia-users/3VsUm2TMQvk). I'm using 0.3.6. I guess I'm out of luck.

**Comment by andreasnoack** [comment]
Have you seen my reply there?

**Comment by dpo** [comment]
Sorry for cross-posting. Thanks!
