### ISSUE TITLE
reshape_view with slices

### ISSUE THREAD

**Issue by robertdj** [JuliaLang/ArrayViews.jl#42]
This is not so much an issue as a question. You mention in the README that slices now provide the same features as this package. I'm a big fan of `reshape_view` -- can the behaviour of this function be obtained with slices?

**Comment by timholy** [comment]
See https://github.com/JuliaLang/julia/pull/15449

**Comment by robertdj** [comment]
If I understand this correctly, it's on it's way?

**Comment by timholy** [comment]
Yes.
