### ISSUE TITLE
Support for reshape

### ISSUE THREAD

**Issue by lendle** [JuliaLang/ArrayViews.jl#9]
Currently reshape on a view falls back to the method for AbstractArray, which performs a copy. 

For ContiguousView at least, it seems like you'd just need a call to [`contiguous_view(v::ContiguousView, shp::Dims)`](https://github.com/lindahua/ArrayViews.jl/blob/1f7453eced491217ae382e786621574ac75576f2/src/ArrayViews.jl#L49). This seemed to work for me:
```julia
 Base.reshape(v::ContiguousView, dims::Int...) = contiguous_view(v, dims)
```
but if doesn't throw an error if `prod(dims)!=prod(v.shp)` and I'm not sure what the behavior should be.

**Comment by lindahua** [comment]
We already have ``reshape_view``.
